<?php
/**
 * Register ACF fields for Panino CPT - Menu Page Fields
 */
if ( function_exists('acf_add_local_field_group') ) :

acf_add_local_field_group(array(
    'key' => 'group_panino_menu_fields',
    'title' => 'Dettagli Menù Panino',
    'fields' => array(
        array(
            'key' => 'field_panino_prezzo_medium',
            'label' => 'Prezzo Medium',
            'name' => 'prezzo_medium',
            'type' => 'number',
            'instructions' => 'Prezzo size Medium (per frittini/dolci: prezzo unico)',
            'required' => 1,
            'wrapper' => array('width' => '33'),
            'default_value' => '',
            'placeholder' => '7.00',
            'prepend' => '€',
            'min' => 0,
            'step' => '0.10',
        ),
        array(
            'key' => 'field_panino_prezzo_large',
            'label' => 'Prezzo Large',
            'name' => 'prezzo_large',
            'type' => 'number',
            'instructions' => 'Prezzo size Large. Lasciare vuoto per voci flat (frittini/dolci).',
            'required' => 0,
            'wrapper' => array('width' => '33'),
            'default_value' => '',
            'placeholder' => '10.00',
            'prepend' => '€',
            'min' => 0,
            'step' => '0.10',
        ),
        array(
            'key' => 'field_panino_prezzo_xxl',
            'label' => 'Prezzo XXL',
            'name' => 'prezzo_xxl',
            'type' => 'number',
            'instructions' => 'Prezzo size XXL. Lasciare vuoto per voci flat (frittini/dolci).',
            'required' => 0,
            'wrapper' => array('width' => '34'),
            'default_value' => '',
            'placeholder' => '17.00',
            'prepend' => '€',
            'min' => 0,
            'step' => '0.10',
        ),
        array(
            'key' => 'field_panino_ingredienti',
            'label' => 'Ingredienti',
            'name' => 'ingredienti',
            'type' => 'textarea',
            'instructions' => 'Lista degli ingredienti',
            'required' => 0,
            'wrapper' => array('width' => '100'),
            'default_value' => '',
            'placeholder' => 'Mortadella, burrata, granella di pistacchio, rucola',
            'rows' => 2,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_panino_allergeni',
            'label' => 'Allergeni',
            'name' => 'allergeni',
            'type' => 'textarea',
            'instructions' => 'Lista degli allergeni',
            'required' => 0,
            'wrapper' => array('width' => '100'),
            'default_value' => '',
            'placeholder' => 'Glutine (grano), Latte',
            'rows' => 2,
            'new_lines' => 'br',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'panino',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Campi prezzo per size + ingredienti.',
    'show_in_rest' => 1,
));

endif;
