<?php
/**
 * Register ACF fields for Social Reels section
 */
if ( ! function_exists('acf_add_local_field_group') ) return;

acf_add_local_field_group(array(
    'key'    => 'group_social_reels',
    'title'  => 'Social Reels',
    'fields' => array(
        array(
            'key'           => 'field_social_reels_titolo',
            'label'         => 'Titolo',
            'name'          => 'social_reels_titolo',
            'type'          => 'text',
            'instructions'  => 'Titolo grande della sezione (es. SEGUICI SU TUTTI I SOCIAL!)',
            'default_value' => 'SEGUICI SU TUTTI I SOCIAL!',
        ),
        array(
            'key'          => 'field_social_reels_sottotitolo',
            'label'        => 'Sottotitolo',
            'name'         => 'social_reels_sottotitolo',
            'type'         => 'textarea',
            'instructions' => 'Testo descrittivo sotto il titolo.',
            'rows'         => 2,
            'new_lines'    => 'br',
        ),
        // Social buttons
        array(
            'key'          => 'field_social_reels_instagram_link',
            'label'        => 'Link Instagram',
            'name'         => 'social_reels_instagram_link',
            'type'         => 'url',
            'instructions' => 'URL del profilo Instagram.',
            'wrapper'      => array('width' => '33'),
        ),
        array(
            'key'          => 'field_social_reels_tiktok_link',
            'label'        => 'Link TikTok',
            'name'         => 'social_reels_tiktok_link',
            'type'         => 'url',
            'instructions' => 'URL del profilo TikTok.',
            'wrapper'      => array('width' => '33'),
        ),
        array(
            'key'          => 'field_social_reels_youtube_link',
            'label'        => 'Link YouTube',
            'name'         => 'social_reels_youtube_link',
            'type'         => 'url',
            'instructions' => 'URL del canale YouTube.',
            'wrapper'      => array('width' => '33'),
        ),
        // Video slots (1-6)
        array(
            'key'   => 'field_social_reels_tab_video',
            'label' => 'Video / Reels',
            'type'  => 'tab',
        ),
        array(
            'key'          => 'field_social_reels_video_1_thumb',
            'label'        => 'Video 1 - Thumbnail',
            'name'         => 'social_reels_video_1_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_1_link',
            'label'   => 'Video 1 - Link',
            'name'    => 'social_reels_video_1_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
        array(
            'key'          => 'field_social_reels_video_2_thumb',
            'label'        => 'Video 2 - Thumbnail',
            'name'         => 'social_reels_video_2_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_2_link',
            'label'   => 'Video 2 - Link',
            'name'    => 'social_reels_video_2_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
        array(
            'key'          => 'field_social_reels_video_3_thumb',
            'label'        => 'Video 3 - Thumbnail',
            'name'         => 'social_reels_video_3_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_3_link',
            'label'   => 'Video 3 - Link',
            'name'    => 'social_reels_video_3_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
        array(
            'key'          => 'field_social_reels_video_4_thumb',
            'label'        => 'Video 4 - Thumbnail',
            'name'         => 'social_reels_video_4_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_4_link',
            'label'   => 'Video 4 - Link',
            'name'    => 'social_reels_video_4_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
        array(
            'key'          => 'field_social_reels_video_5_thumb',
            'label'        => 'Video 5 - Thumbnail',
            'name'         => 'social_reels_video_5_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_5_link',
            'label'   => 'Video 5 - Link',
            'name'    => 'social_reels_video_5_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
        array(
            'key'          => 'field_social_reels_video_6_thumb',
            'label'        => 'Video 6 - Thumbnail',
            'name'         => 'social_reels_video_6_thumb',
            'type'         => 'image',
            'return_format'=> 'array',
            'preview_size' => 'medium',
            'mime_types'   => 'jpg,jpeg,png,webp',
            'wrapper'      => array('width' => '50'),
        ),
        array(
            'key'     => 'field_social_reels_video_6_link',
            'label'   => 'Video 6 - Link',
            'name'    => 'social_reels_video_6_link',
            'type'    => 'url',
            'wrapper' => array('width' => '50'),
        ),
    ),
    'location' => array(
        array(
            array(
                'param'    => 'page_template',
                'operator' => '==',
                'value'    => 'template-homepage.php',
            ),
        ),
    ),
    'menu_order' => 20,
    'position'   => 'normal',
    'style'      => 'default',
    'active'     => true,
));
